apiVersion: v1
kind: Service
metadata:
  name: biblioteca-digital-service
spec:
  type: LoadBalancer
  selector:
    app: biblioteca-digital
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080